## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

### 索引
####   ```argmin()```和```argmax()```是求最大值和最小值的所在的索引位置

In [3]:
np.argmin(x)

24221

In [4]:
x[886266]

1.1462137602262732

In [5]:
np.min(x)

-4.935714319667308

In [6]:
np.argmax(x)

531371

In [7]:
x[4851]

0.13342432766862283

In [8]:
np.max(x)

5.317091893863436

### 排序和使用索引

In [9]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

> ```np.random.shuffle(x)``` 将数组x乱序

In [10]:
np.random.shuffle(x)
x

array([ 9,  5,  8,  7,  6, 13, 15, 12,  3, 11, 10, 14,  2,  4,  0,  1])

In [11]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x

array([ 9,  5,  8,  7,  6, 13, 15, 12,  3, 11, 10, 14,  2,  4,  0,  1])

In [13]:
x.sort()

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
X = np.random.randint(10, size=(4,4))
X

array([[6, 4, 9, 0],
       [8, 2, 0, 2],
       [9, 1, 4, 5],
       [8, 0, 0, 8]])

In [16]:
np.sort(X, axis=0)

array([[6, 0, 0, 0],
       [8, 1, 0, 2],
       [8, 2, 4, 5],
       [9, 4, 9, 8]])

In [17]:
np.sort(X, axis=1)

array([[0, 4, 6, 9],
       [0, 2, 2, 8],
       [1, 4, 5, 9],
       [0, 0, 8, 8]])

#### 使用索引

In [18]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.random.shuffle(x)

In [20]:
x

array([ 4,  7,  8, 14,  3, 15, 11,  6, 10,  5,  2, 12,  0, 13,  9,  1])

In [21]:
np.argsort(x)

array([12, 15, 10,  4,  0,  9,  7,  1,  2, 14,  8,  6, 11, 13,  3,  5],
      dtype=int64)

In [22]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4, 15, 11,  7, 10,  5, 14, 12,  8, 13,  9,  6])

In [23]:
np.argpartition(x, 3)

array([12, 15, 10,  4,  0,  5,  6,  1,  8,  9,  3, 11,  2, 13, 14,  7],
      dtype=int64)

In [24]:
X

array([[6, 4, 9, 0],
       [8, 2, 0, 2],
       [9, 1, 4, 5],
       [8, 0, 0, 8]])

In [25]:
np.argsort(X, axis=1)

array([[3, 1, 0, 2],
       [2, 1, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 0, 3]], dtype=int64)

In [26]:
np.argpartition(X, 2, axis=1)

array([[3, 1, 0, 2],
       [2, 1, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 0, 3]], dtype=int64)