## 10 ``Numpy`` 中的比较和Fancy Indexing

### Fancy Indexing

In [34]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
x[3]

3

In [36]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [37]:
x[3:9:2]

array([3, 5, 7])

In [38]:
[x[3], x[5], x[8]]

[3, 5, 8]

In [39]:
ind = [3, 5, 8]
x[ind]

array([3, 5, 8])

In [40]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

#### Fancy Indexing 应用在二维数组

In [41]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [43]:
X[0, col]

array([1, 2, 3])

In [44]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [45]:
col = [True, False, True, True]

In [46]:
X[0, col]

array([0, 2, 3])

### ``numpy.array`` 的比较

In [47]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [49]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [50]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [51]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [52]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [53]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [54]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [55]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### 使用 ``numpy.array`` 的比较结果 

In [75]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
np.count_nonzero?

In [94]:
np.count_nonzero( x <= 3)

4

In [80]:
np.sum(x <= 3)

4

In [58]:
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [59]:
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [60]:
np.any(x == 0)

True

In [61]:
np.any(x < 0)

False

In [62]:
np.all(x > 0)

False

In [63]:
np.all(x >= 0)

True

In [64]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [65]:
np.sum((x > 3) & (x < 10))

6

In [98]:
(x > 3) & (x < 10)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False])

In [66]:
np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-66-d834f65999a2>, line 1)

In [67]:
np.sum((x % 2 == 0) | (x > 10))

11

In [68]:
np.sum(~(x == 0))

15

### 比较结果和Fancy Indexing

In [69]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [70]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [71]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [99]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
X[X[:,3] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])