## 04 创建 ``numpy.array``

In [4]:
import numpy as np

### ``numpy.array``

In [5]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 其他创建 ``numpy.array`` 的方法

### ``zeros`` 创建全0矩阵

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### ```ones``` 创建全1矩阵

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### ```full``` 创建指定数值的矩阵

In [12]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [13]:
np.full(fill_value=666, shape=(3, 5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### ```arange``` 与Python中```range```函数相对应，其中步长参数可以是浮点数

In [14]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
[i for i in range(0, 1, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(0, 1, 0.2)

In [ ]:
[i for i in range(0, 10)]

In [ ]:
np.arange(0, 10)

In [ ]:
[i for i in range(10)]

In [ ]:
np.arange(10)

### ```linspace``` 表示在0-20区间内截取10个点形成数组，每个数的间距是相同的。如下

In [ ]:
np.linspace(0, 20, 10)

In [ ]:
np.linspace(0, 20, 11)

In [ ]:
np.linspace(0, 1, 5)

### ```random```

#### ```randint```

In [ ]:
np.random.randint(0, 10)    # [0, 10)之间的随机数

In [ ]:
np.random.randint(0, 10, 10)

In [ ]:
np.random.randint(0, 1, 10)

In [ ]:
np.random.randint(0, 10, size=10)

In [ ]:
np.random.randint(0, 10, size=(3,5))

In [ ]:
np.random.randint(10, size=(3,5))

#### ```seed``` 随机种子

In [ ]:
np.random.seed(666)

In [ ]:
np.random.randint(0, 10, size=(3, 5))

In [ ]:
np.random.seed(666)
np.random.randint(0, 10, size=(3,5))

#### ```random``` 生成0-1的随机浮点数

In [ ]:
np.random.random()

In [ ]:
np.random.random((3,5))

#### ```normal``` 形成一个均值为0方差为1的浮点数，取正态分布的随机数

In [ ]:
np.random.normal()

生成一个均值为10，方差为100的正态分布的随机数

In [ ]:
np.random.normal(10, 100)

生成一个均值为0，方差为1的正态分布的随机数矩阵

In [ ]:
np.random.normal(0, 1, (3, 5))

#### `np.random.<TAB>` 查看random中的更多方法

In [ ]:
np.random?

In [ ]:
np.random.normal?

In [ ]:
help(np.random.normal)